apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: post-ui
  name: post-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: post-ui
    spec:
      containers:
        - image: reckue/post-ui:latest
          name: post-ui
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 64Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: post-ui
  name: post-ui
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: post-ui
  type: ClusterIP
status:
  loadBalancer: {}
